#!/bin/bash

url=$(jq -r '.registry + "/" + .name + ":" + .tag' /etc/abroot/abroot.json)
if [ $url = "ghcr.io/vanilla-os/nvidia-exp:main" ]; then
	abroot rebase ghcr.io/vanilla-os/gnome-nvidia-modern:latest --rebase-only
fi
